---
- name: Copy private key / certificate for DoH
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/unbound/{{ item.split('/') | last }}
    owner: root
    group: root
    mode: '0400'
  with_items:
    - "{{ dot_key }}"
    - "{{ dot_crt }}"
